name: linting, testing
on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: [14, 16]

        steps:
            - name: Checkout Commit
              uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}
            - name: installing modules
              uses: npm install
            - name: run prod build
              uses: npm run build:prod
            - name: run lint ts
              uses: npm run lint:ts
            - name: run lint scss
              uses: npm run lint:scss
            - name: run unit
              uses: npm run unit
